Pythin2/__init__.py
from flask import Flask
from dotenv import load_dotenv
from .main import main_bp as main_blueprint
from .user import user_bp as user_blueprint
import os

#Load .env file
dotenv_path = dotenv_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '.env'))
load_dotenv(dotenv_path)

# Create the application
def create_app():
    app = Flask(__name__)
    
    # App configurations
    app.config['SECRET_KEY'] = os.getenv('PYTHIN2_SECRET_KEY')
    app.debug = True

    # Register blueprints
    app.register_blueprint(main_blueprint)
    app.register_blueprint(user_blueprint)

    # Print routes
    print("Routes:")
    for rule in app.url_map.iter_rules():
        print(f"{rule.endpoint}: {rule}")

    # Debugging
    print("App created succesfully")

    return app

Pythin2/game/__init__.py
from flask import Blueprint

game_bp = Blueprint('game', __name__)

from . import views

Pythin2/game/views.py
from flask import Blueprint, render_template
from .levels import *
from . import game_bp

@game_bp.route('/level<level>')
def play():
    return render_template('level.html', level=level)

Pythin2/main/__init__.py
from flask import Blueprint

main_bp = Blueprint('main', __name__)

from . import views

Pythin2/main/views.py
from flask import Blueprint, render_template
from . import main_bp

@main_bp.route('/')
def index():
    print("Index page being rendered...")
    return render_template('index.html')

@main_bp.route('/about')
def about():
    print("About page being rendered...")
    return render_template('about.html')

Pythin2/user/__init__.py
from flask import Blueprint

user_bp = Blueprint('user', __name__)

from . import views

Pythin2/user/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from ..database.db import user_db
from . import user_bp

@user_bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        print("Login page being rendered...")
        username = request.form['username']
        password = request.form['password']
        if user_db.login_user(username, password):
            print(f"{username} logged in")
            return redirect(url_for('main.index'))
        else:
            print("Login failed")
            return render_template('user.html', type='login', failed=True)
    else:
        print("Login page being rendered...")
        return render_template('user.html', type='login', failed=False)

@user_bp.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        print("Registering user...")
        email = request.form['email']
        username = request.form['username']
        password = request.form['password']
        if user_db.register_user(email, username, password):
            print(f"{username} registered")
            return redirect(url_for('main.index'))
        else:
            print("Registration failed")
            return render_template('user.html', type='register', failed=True)
    else:
        print("Register page being rendered...")
        return render_template('user.html', type='register', failed=False)
    
@user_bp.route('/verify/<code>')
def verify(code):
    print("Verifying user...")
    if user_db.verify_user(code):
        print("User verified")
        return redirect(url_for('main.index'))
    else:
        print("Verification failed")
        return redirect(url_for('main.index'))

Pythin2/templates/about.html
<!DOCTYPE html>
<html>

<head>
    <title>Pythin2</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
</head>

<body>
    <div class="top">
        <div class="right-container">
            <button class="login-button" onclick="window.location.href='/login.html'">Login</button>
            <button class="register-button">Register</button>
        </div>
    </div>
    <div class="content">
        <div class="center-container">
            <h1 class="welcome">Welcome to Pythin2</h1>
        </div>
        <div class="center-container">
            <button class="play-button">Play</button>
        </div>
    </div> 
</body>

</html>

Pythin2/templates/index.html
<!DOCTYPE html>
<html>

<head>
    <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.11"></script>
    <title>Pythin2</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
</head>

<body>
    <div class="top">
        <div class="right-container">
            <button class="login-button" onclick="window.location.href='/login'">Login</button>
            <button class="register-button" onclick="window.location.href='/register'">Register</button>
        </div>
    </div>
    <div class="content">
        <div class="center-container">
            <h1 id="welcome"></h1>
        </div>
        <script>
            var status = "{{ status }}";
            var strings = ['Welcome to Pythin2']
            var typed = new Typed('#welcome', {
                strings: strings,
                typeSpeed: 50,
                startDelay: 500,
                loop: false,
                showCursor: false,
            });
        </script>
        <div class="center-container">
            <button class="play-button" onclick="window.location.href='/level'">Play</button> 
        </div>
    </div>

Pythin2/templates/level-selection.html
<!DOCTYPE html>
<html>
<head>
    <title>Levels</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/level.css') }}">
</head>
<body>
    <h1>Levels</h1>
    <div class="level-container">
        {% for i in range(1, 11) %}
            {% if loop.index0 % 4 == 0 %}
                <div class="row">
            {% endif %}
            {% if i in passed %}
                <button class="passed" onclick="window.location.href='/level/{{ i }}'">Level {{ i }}</button>
            {% elif i in attempted %}
                <button class="attempted" onclick="window.location.href='/level/{{ i }}'">Level {{ i }}</button>
            {% else %}
                <button class="unattempted" onclick="window.location.href='/level/{{ i }}'">Level {{ i }}</button>
            {% endif %}
            {% if loop.index0 % 4 == 3 or loop.last %}
                </div>
            {% endif %}
        {% endfor %}
    </div>
</body>

Pythin2/templates/level.html
<!DOCTYPE html>
<html>
<head>
    <title>level {{ level }}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/user.css') }}">
</head>
<body>
    <h1>level {{ level }}</h1>
</body>
</html>

Pythin2/templates/tutorial.html
<!DOCTYPE html>
<html>
<head>
    <title>Tutorial</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/level.css') }}">
</head>
<body>
    <h1>Tutorial</h1>
</body>
</html>

Pythin2/templates/user.html
<!DOCTYPE html>
<html>
<head>
    <title>
        {% if type == 'login' %}
            Login
        {% else %}
            Register
        {% endif %}
    </title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/user.css') }}">
</head>
<body>
    <div class="center-container" id="outer-container">
        <div class="user-container" id="{% if type == 'login' %}
            login-container
        {% else %}
            register-container
        {% endif %}">
            <h1>
                {% if type == 'login' %}
                    Login
                {% else %}
                    Register
                {% endif %}
            </h1>
            <form action="{% if type == 'login' %}
                {{ url_for('user.login') }}
            {% else %}
                {{ url_for('user.register') }}
            {% endif %}" method="POST">
                <input type="text" id="username" name="username" placeholder="Enter username" required>
                <input type="password" id="password" name="password" placeholder="Enter password" required>
                <button type="submit">
                    {% if type == 'login' %}
                        Login
                    {% else %}
                        Register
                    {% endif %}
                </button>
            </form>
            {% if failed %}
                {% if type == 'login' %}
                    <p class="warning">Incorrect username or password!</p>
                {% else %}
                    <p class="warning">User already exists!</p>
                {% endif %}
            {% endif %}
        </div>
    </div>
</body>
</html>